export class homeTitle{
  id?:number
  image?:Resource
  name?:string
}
export const homeTitleDate:homeTitle[] = [
  {
    id:0,
    image:$r("app.media.phone"),
    name:"手机"
  },
  {
    id:1,
    image:$r("app.media.win"),
    name:"电脑"
  },
  {
    id:2,
    image:$r("app.media.pb"),
    name:"平板"
  },
  {
    id:3,
    image:$r("app.media.food"),
    name:"美食"
  },
  {
    id:4,
    image:$r("app.media.wm"),
    name:"外卖"
  },
  {
    id:5,
    image:$r("app.media.xyj"),
    name:"家电"
  },
  {
    id:6,
    image:$r("app.media.jj"),
    name:"家具"
  },
  {
    id:7,
    image:$r("app.media.paic"),
    name:"买菜"
  },
  {
    id:8,
    image:$r("app.media.qt"),
    name:"其他"
  }
]



export interface  listData {
  id: string,
  image: string,
  title:string,
  price: number
}
export const listDatass:listData[]=[
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  },
  {
    id:"0",
    image:"https://cdn.cnbj1.fds.api.mi-img.com/nr-pub/202410281157_6e91e1273cb084794dd8301ae6353159.png?thumb=1&w=250&h=250&f=webp&q=90",
    title:"REDMI K80 Pro",
    price:1999
  }
]